---------------
-- Language
---------------
Language = {
    ["QBTarget"] = {
        ["Information"] = "Trucker Information",
        ["IconInformation"] = "fas fa-truck",
        ["Delivery"] = "Deliver Order",
        ["IconDelivery"] = "fas fa-box",
        ["Vehicle"] = "Save Vehicle",
        ["IconVehicle"] = "fas fa-car",
        ["PayslipLv1"] = "Level 1 Payslip",
        ["PayslipLv2"] = "Level 2 Payslip",
        ["PayslipLv3"] = "Level 3 Payslip",
        ["GeneralMenu"] = "General Menu",
    },
    ["QBMenu"] = {
        ["Information"] = "Trucker Information",
        ["StartJob"] = "Start a delivery!",
        ["Locations"] = "Trucker Locations",
        ["SmallDelivery"] = "Small Delivery (1.0km/2.0km)",
        ["MediumDelivery"] = "Medium Delivery (3.0km/4.0km)",
        ["BigDelivery"] = "Big Delivery (+5.0km)",
        ["Experience"] = "Your Experience: ",
        ["GainExperience"] = "Experience :",
        ["TripsTaken"] = "Trips Taken:",
        ["Kilometers"] = "Kilometers Traveled:",
        ["Need"] = "Need: ",
        ["Rewards"] = "Rewards: ",
        ["Money"] = "Money: $",
        ["Company"] = "Trucker Company",
        ["MenuEmployee"] = "Employee Menu",
        ["DescMenuEmplyee"] = "Access employee menu",
        ["BossMenu"] = "Boss Menu",
        ["DescBossMenu"] = "Access owners boss menu",
        ["CheckLevel"] = "Check My Reputation",
        ["BuyTruck"] = "Buy Truck",
        --[[ ["PreviewTruck"] = "[👀] Preview Truck", ]]
        ["TruckerShop"] = "Open Truck Shop",
        ["Buy"] = "Purchase : ",
        ["For"] = "For : ",
        ["Currency"] = "$",
        ["Back"] = "⬅ Back",
        ["PreviewMenu"] = "Preview Menu",
        ["Preview"] = "Preview:",
        ["Press"] = "Press",
        ["ToClose"] = "To Close",
    },
    ["Notification"] = {
        ["SaveVehicle"] = "Deliver contract!.",
        ["Entregue"] = "Order delivered, head back to depot.",
        ["Failed"] = "You failed.",
        ["NoXP"] = "You don't have enough experience.",
        ["SpawnBlocked"] = "Spawn Blocked",
        ["PickUpTrailer"] = "Pick up the trailer.",
        ["JobErrado"] = "You don't work for this company.",
        ["VeiculoErrado"] = "This is not the vehicle i loaned you. Cancels the trip and start again.",
        ["WrongVehicle"] = "Wrong vehicle.",
        ["Trailer"] = "Please make sure you attach the trailer for a successfull mission",
        ["Reciept"] = "Please take this reciept to the boss to get paid by submitting the vehicle",
        ["Truck"] = "You are not in the truck",
        ["Level"] = "Your Trucker Job level is: ",
        ["MenuOpen"] = "Someone is in the menu please wait!",
        ["Bought"] = "Vehicle successfully bought!",
        ["NoMoney"] = "You dont have enough money!",
        ["NoTrailer"] = "You dont have any trailer on your truck",
        ["StartMission"] = "You need start mission first.",
        ["NoContract"] = "You don't have any trucker contract with you.",
    },
    ["ProgressBars"] = {
        ["Entregar"] = "Delivering order..."
    },
    ["QBInput"] = {
        ["ChoosePayment"] = "Choose Payment Method",
        ["Choose"] = "Choose",
        ["PaymentType"] = "Payment Type",
        ["Cash"] = "Cash",
        ["Bank"] = "Bank",
    }
}
